### ISSUE TITLE
Readme.md is outdated, the examples will not run properly.

### ISSUE THREAD

**Issue by LouisGameDev** [martmists/asynctwitch#11]
I've just discovered my bots weren't saying anything is because you have to change this

```
# Example command:
@bot.command('example', alias=['moreexample','anothaone'], desc='example command')
async def example(message, word1:str, number1:int, rest:str):
    bot.say('wow');

```

to this

```
# Example command:
@bot.command('example', alias=['moreexample','anothaone'], desc='example command')
async def example(message, word1:str, number1:int, rest:str):
    await bot.say('channel', 'wow');

```

**Comment by LouisGameDev** [comment]
Do you mind explaining?

**Comment by Martmists-GH** [comment]
I fixed the Readme, it should now show proper examples

**Comment by LouisGameDev** [comment]
The example still does not work. `Bot.say` is a coroutine and needs `await` to execute.
